apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: platformapis.operator.ibm.com
  labels:
    name: platformapis.operator.ibm.com
    app.kubernetes.io/instance: platformapis.operator.ibm.com
    app.kubernetes.io/managed-by: platformapis.operator.ibm.com
    app.kubernetes.io/name: platformapis.operator.ibm.com
spec:
  group: operator.ibm.com
  names:
    kind: PlatformAPI
    listKind: PlatformAPIList
    plural: platformapis
    singular: platformapi
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
