apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ibm-platform-api-operator
  labels:
    name: ibm-platform-api-operator
    app.kubernetes.io/instance: platform-api
    app.kubernetes.io/managed-by: platformapis.operator.ibm.com
    app.kubernetes.io/name: platformapis.operator.ibm.com
subjects:
- kind: ServiceAccount
  name: ibm-platform-api-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ibm-platform-api-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ibm-platform-api-operator
  labels:
    name: ibm-platform-api-operator
    app.kubernetes.io/instance: platformapis.operator.ibm.com
    app.kubernetes.io/managed-by: platformapis.operator.ibm.com
    app.kubernetes.io/name: platformapis.operator.ibm.com
subjects:
- kind: ServiceAccount
  name: ibm-platform-api-operator
  namespace: REPLACE_NAMESPACE
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ibm-platform-api-operator