channels:
- currentCSV: ibm-platform-api-operator.v3.6.1
  name: dev
- currentCSV: ibm-platform-api-operator.v3.6.0
  name: beta
- currentCSV: ibm-platform-api-operator.v3.5.0
  name: stable-v1
defaultChannel: stable-v1
packageName: ibm-platform-api-operator-app
