channels:
  - currentCSV: ibm-platform-api-operator.v3.7.2
    name: dev
  - currentCSV: ibm-platform-api-operator.v3.7.1
    name: beta
  - currentCSV: ibm-platform-api-operator.v3.7.1
    name: stable-v1
defaultChannel: stable-v1
packageName: ibm-platform-api-operator-app
